// errors.ts

export const ErrorCode = {
	// 通用错误
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	NOT_FOUND: "NOT_FOUND",
	BAD_REQUEST: "BAD_REQUEST",
	CONFLICT: "CONFLICT",
	PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
	UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

	// 数据库相关错误
	DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
	DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
	DATABASE_TIMEOUT: "DATABASE_TIMEOUT",

	// 身份验证和授权错误
	AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	ACCESS_DENIED: "ACCESS_DENIED",

	// 用户相关错误
	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	INVALID_USER_CREDENTIALS: "INVALID_USER_CREDENTIALS",

	// 文件上传和处理错误
	FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
	FILE_FORMAT_NOT_SUPPORTED: "FILE_FORMAT_NOT_SUPPORTED",
	FILE_SIZE_EXCEEDED: "FILE_SIZE_EXCEEDED",

	// API调用和网络错误
	API_CALL_FAILED: "API_CALL_FAILED",
	NETWORK_ERROR: "NETWORK_ERROR",
	TIMEOUT_ERROR: "TIMEOUT_ERROR",

	// RSS模块相关错误
	RSS_SOURCE_EXISTS: "RSS_SOURCE_EXISTS",
	RSS_SOURCE_NOT_FOUND: "RSS_SOURCE_NOT_FOUND",
	RSS_PARSER_ERROR: "RSS_PARSER_ERROR",
	RSS_FETCH_ERROR: "RSS_FETCH_ERROR",
	RSS_INVALID_URL: "RSS_INVALID_URL",

	// 自定义模块相关错误（可扩展）
	// ExampleModule
	EXAMPLE_MODULE_ERROR: "EXAMPLE_MODULE_ERROR",
};
